import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App';
// amplify_outputs.json is generated by `ampx sandbox` or `ampx generate outputs`
// It will not exist until you run the Amplify sandbox for the first time.
// For CI, run: npx ampx generate outputs --app-id <id> --branch main
// @ts-ignore
import outputs from './amplify_outputs.json';

Amplify.configure(outputs);

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60,    // 1 minute
      retry: 1,
    },
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </React.StrictMode>,
);
