import { defineStorage } from '@aws-amplify/backend';

export const storage = defineStorage({
  name: 'freightStorage',
  access: (allow) => ({
    // Carrier rate card CSV/Excel uploads — broker uploads, Lambda reads
    'rate-cards/{entity_id}/*': [
      allow.entity('identity').to(['read', 'write', 'delete']),
      allow.groups(['Brokers']).to(['read', 'write', 'delete']),
    ],
    // Carrier invoice CSV/PDF uploads — broker uploads
    'carrier-invoices/{entity_id}/*': [
      allow.entity('identity').to(['read', 'write', 'delete']),
      allow.groups(['Brokers']).to(['read', 'write', 'delete']),
    ],
    // Connote labels — generated by Lambda, read by all authenticated users
    'connote-labels/{entity_id}/*': [
      allow.entity('identity').to(['read']),
      allow.authenticated.to(['read']),
    ],
    // Proof of Delivery documents — stored by Lambda
    'pod-documents/{entity_id}/*': [
      allow.entity('identity').to(['read']),
      allow.authenticated.to(['read']),
    ],
    // Exported reports — pre-signed URLs, short-lived read access
    'reports/{entity_id}/*': [
      allow.entity('identity').to(['read', 'write', 'delete']),
      allow.groups(['Brokers', 'WarehouseAdmins', 'TenantUsers']).to(['read']),
    ],
  }),
});
